config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", unlocks: "users/unlocks", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations" }
  root to: 'products#index'

  resources :products

  resources :suppliers

  resources :images

  resources :orders

  resources :carted_products

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :supplier
  has_many :images
  belongs_to :user
  
  has_many :carted_products
  has_many :orders, through: :carted_products

  has_many :categorized_products
  has_many :categories, through: :categorized_products

  validates :user, :supplier, :name, :description, :price, presence: true
  validates :price, length: {in: 4..5}

  accepts_nested_attributes_for :images

  def self.discount
    1.00
  end
  def self.random_id
    product_id = []
    Product.all.each do |product|
      product_id << product.id
    end
    product_id[rand(0..product_id.length - 1)]
  end

  def price_dollar_form(value)
    "$#{sprintf("%.2f", value)}"
  end
  def discount_message
    if price <= Product.discount
      "Discount Item!!!"
    else
      "On Sale!!!"
    end
  end
  def tax_calc
    price * 9 / 100
  end
  def total_price
    price + tax_calc
  end
  def instock_message
    if instock == true
      "Currently In Stock"
    else
      "Not Currently In Stock"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, only: [:create, :update, :destroy]
  def index
    if current_user
      if !current_user.orders.find_by(open: true)
        redirect_to "/orders"
      end
    end
    if params[:order] == "PHtoL"
      @products = Product.all.order(price: :desc)
    elsif params[:order] == "PLtoH"
      @products = Product.all.order(:price)
    elsif params[:category]
      @products = Category.find_by(id: params[:category].to_i).products
    else
      @products = Product.all.order(:name)
    end
    if params[:discount] == "true"
      @products = @products.where("price < ?", Product.discount )
    elsif params[:commit] == "Search"
      @products = @products.where("name LIKE ?", "%#{params[:search]}%")
    end
  end
  def create
      @product = Product.new(product_params)
      @product.attributes = {user_id: current_user.id}
    if @product.save
      redirect_to "/products/#{Product.last.id}"
      flash[:success] = "Product Created"
    else
      render :new
      flash[:warning] = "Product Not Created"
    end
  end
  def new
    @product = Product.new
    @product.images.build
  end
  def show
    @product = Product.find_by(id: params[:id])
  end
  def edit
    @product = Product.find_by(id: params[:id])
    @product.images.build
  end
  def update
    @product = Product.find_by(id: params[:id])
    if @product.update(product_params)
      flash[:info] = "Product Updated"
      redirect_to "/products/#{Product.find_by(id: params[:id]).id}"
    else
      flash[:warning] = "Product Not Updated"
      render :edit
    end
  end
  def destroy
    Product.find_by(id: params[:id]).destroy
    redirect_to "/products"
    flash[:warning] = "Product Deleted"
  end

  private

  def product_params
    params.require(:product).permit(:id, :name, :price, :description, :instock, :user_id, :supplier_id, images_attributes: [:url])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class = "container-fluid">
  <div class = "col-md-4"></div>
  <div class = "col-md-4">
    <%= form_for @product do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :instock? %>
        <%= f.check_box :instock %>
      </div>
      <div class="form-group">
        <%= f.label :supplier_id %>
        <%=f.collection_select :supplier_id, Supplier.all, :id, :company_name%>
      </div>
      <div class="form-group center-text">
        <%= f.submit "Add Product", class: "btn btn-default btn-lg center-text" %>
      </div>
    <% end %>
    <div class="form-group center-text">
      <%= link_to "Abort Mission", "/products", class: "btn btn-default btn-lg" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class = "container-fluid">
  <div class = "row">
    <% @products.each_with_index do |product, index| %>
      <div class = "col-md-3" >
        <a href="/products/<%= product.id %>">
          <div class = "index-item">
                <div>
                  <img class = "img-responsive img-rounded" src=<%= product.images.first.url %>>
                </div>  
                <div>
                  <button class = "btn btn-lg"><%= "#{product.name} - #{product.price_dollar_form(product.price)}" %></button>
                </div>
          </div>  
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class = "container-fluid">
  <div class = "col-md-4"></div>
  <div class = "col-md-4">
    <%= form_for @product do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :instock? %>
        <%= f.check_box :instock %>
      </div>
      <div class="form-group">
        <%= f.label :supplier_id %>
        <%= f.collection_select :supplier_id, Supplier.all, :id, :company_name%>
      </div>
      <%= f.fields_for :images do |ff| %>
        <div class="form-group">
          <%= ff.label :url, "Image URL 2" %>
          <%= ff.text_field :url, class: "form-control"%>
        </div>
      <% end %>
      <%= f.fields_for :images do |ff| %>
        <div class="form-group">
          <%= ff.label :url, "Image URL" %>
          <%= ff.text_field :url, class: "form-control"%>
        </div>
      <% end %>
      <div class="form-group center-text">
        <%= f.submit "Add Product", class: "btn btn-default btn-lg" %>
      </div>
    <% end %>
    <div class="form-group center-text">
      <%= link_to "Abort Mission", "/products", class: "btn btn-default btn-lg" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% if @product %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6 individual-product">
        <h3>Product Name</h3>
        <p><%= @product.name %></p>
        <h4 class="discount-message"><%= @product.discount_message %></h4>
        <h3>Product Prices</h3>
        <p>Store Price: <%= @product.price_dollar_form(@product.price) %><br>Tax: <%= @product.price_dollar_form(@product.tax_calc) %><br>Price With Tax: <%= @product.price_dollar_form(@product.total_price) %></p>
        <h3>Product Description</h3>
        <p><%= @product.description %></p>
        <h3>Product Supplier</h3>
        <p><%= @product.supplier.company_name %></p>
        <h3>Product Added By</h3>
        <p><%= @product.user.email %></p>
        <h3>Product Images</h3>
        <% @product.images.each do |image| %>
        <p><img src="<%= image.url %>" class = "img-responsive individual-image"></p>
        <% end %>
        <h3>This Product is <%= @product.instock_message %></h3>
        <% if current_user.admin? %>
        <p><%= link_to "Edit \"#{@product.name}\"", edit_product_path, method: :get, class: "btn btn-default btn-lg" %></p>
        <p><%= link_to "Edit Images", "/images?product=#{@product.id}", method: :get, class: "btn btn-default btn-lg" %></p>
        <p><%= link_to "New Image", "/images/new?product=#{@product.id}", method: :get, class: "btn btn-default btn-lg" %></p>
        <p><%= link_to "Permanently Delete \"#{@product.name}\" From The Database", product_path(@product.id), method: :delete, class: "btn btn-default btn-lg" %></p>
        <% end %>
        <p><a href="/products/"><button class = "btn btn-default btn-lg">Back to all products</button></a></p>
      </div>
    </div>
    <% if !current_user.admin? %>
    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 individual-product cart-div">
        <h3>Add <%= "\'#{@product.name}\'" %> To Cart</h3>
          <% if @carted_product && @carted_product.errors.any?%>
            <%@carted_product.errors.full_messages.each do |message| %>
              <p><%= message %>.</p>
            <% end %>
          <% end %>
        <%= form_tag "/carted_products", method: :post do %>
          <div class="form-group quantity-div">
            <p><%= label_tag :quantity %></p>
            <p><%= number_field_tag :quantity, 1, class: "form-control center-text" %></p>
          </div>
          <div class="form-group">
            <p><%= hidden_field_tag :product_id, @product.id %></p>
          </div>
          <div class="form-group">
            <%= submit_tag "Add To Cart", class: "btn btn-lg btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>