config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", unlocks: "users/unlocks", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations" }
  root to: 'products#index'

  resources :products

  resources :suppliers

  resources :images

  resources :orders

  resources :carted_products

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_admin_or_supplier!

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to "/suppliers/#{@supplier.id}"
    else
      render :new
    end
  end

  def show
    @supplier = Supplier.find_by(id: params[:id])
  end

  def edit
    @supplier = Supplier.find_by(id: params[:id])
  end

  def update
    @supplier = Supplier.find_by(id: params[:id])
    if @supplier.update(supplier_params)
      redirect_to "/suppliers/#{@supplier.id}"
    else
      render :edit
    end
  end

  def destroy
    Supplier.find_by(id: params[:id]).update(active: false)
    redirect_to "/suppliers"
  end
  def index
    @suppliers = Supplier.all
  end

  private

  def supplier_params
    params.require(:supplier).permit(:company_name, :first_name, :last_name, :email, :phone, :active)
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/edit.html.erb
<div class = "container-fluid">
  <div class = "col-md-4"></div>
  <div class = "col-md-4">
    <%= form_for @supplier do |f| %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :company_name %>
        <%= f.text_field :company_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group center-text">
        <%= f.submit "Edit Supplier", class: "btn btn-default btn-lg center-text" %>
      </div>
    <% end %>
  </div>
</div>

app/views/suppliers/index.html.erb
<div class = "container-fluid">
  <div class = "row">
    <% @suppliers.each do |supplier| %>
      <div class = "col-md-3" >
        <a href="/suppliers/<%= supplier.id %>">
          <div class = "index-item">
            <h3><br><%= "#{supplier.company_name}" %></h3>
            <p><%= "#{supplier.first_name} #{supplier.last_name}" %></p>
            <p><%= supplier.email %></p>
            <p><%= supplier.phone %></p>
          </div>  
        </a>
      </div>
    <% end %>
  </div>
  <div class = "row">
    <div class = "col-md-4"></div>
    <div class = "col-md-4">
      <p class = "center-text"><%= link_to "Add A New Supplier To The Database", suppliers_new_path%></p>
    </div>
  </div>
</div>

app/views/suppliers/new.html.erb
<div class = "container-fluid">
  <div class = "col-md-4"></div>
  <div class = "col-md-4">
    <%= form_for @supplier do |f| %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :company_name %>
        <%= f.text_field :company_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group center-text">
        <%= f.submit "Add Supplier", class: "btn btn-default btn-lg center-text" %>
      </div>
    <% end %>
  </div>
</div>

app/views/suppliers/show.html.erb
<div class = "container-fluid">
  <div class = "col-md-3">
  </div>
  <div class = "col-md-6 individual-product">
    <h3>Supplier</h3>
    <p><%= @supplier.company_name %></p>
    <h3>Supplier Contact</h3>
    <p><%= "#{@supplier.first_name} #{@supplier.last_name}" %></p>
    <h3>Supplier Email</h3>
    <p><%= link_to "#{@supplier.email}","mailto:#{@supplier.email}" %></p>
    <h3>Supplier Phone</h3>
    <p><%= @supplier.phone %></p>
    <p><%= link_to "Permanently Delete \"#{@supplier.company_name}\" From The Database", supplier_path(@supplier.id), method: :delete, class: "btn btn-default btn-lg" %></p>
    <p><%= link_to "Edit \"#{@supplier.company_name}\"", edit_supplier_path, method: :get, class: "btn btn-default btn-lg" %></p>
    <p><a href="/suppliers"><button class = "btn btn-default btn-lg">Back to all suppliers</button></a></p>
  </div>
</div>