config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", unlocks: "users/unlocks", registrations: "users/registrations", passwords: "users/passwords", confirmations: "users/confirmations" }
  root to: 'products#index'

  resources :products

  resources :suppliers

  resources :images

  resources :orders

  resources :carted_products

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    if params[:product] != nil
      @images = Image.where(product_id: params[:product])
    else
      @images = Image.all
    end
  end
  def new
    if params[:product] != nil
      @fruit_name = Product.find_by(id: params[:product]).name
    else
      @fruit_name = "fruit"
    end
  end
  def create
    product = Product.find_by(name: params[:name])
    if product == nil
      flash[:warning] = "No Product by That Name"
      redirect_to "/images/new"
    else
      Image.create(url: params[:url], product_id: product.id)
      redirect_to "/images/#{Image.last.id}"
      flash[:success] = "Image Created"
    end
  end
  def show
    @image = Image.find_by(id: params[:id].to_i)
  end
  def edit
    @image = Image.find_by(id: params[:id].to_i)
  end
  def update
    Image.update(name: params[:name], email: params[:email], phone: params[:phone])
    flash[:info] = "Image Updated"
    redirect_to = "/images/#{Image.find_by(id: params[:id]).id}"
  end
  def destroy
    Image.find_by(id: params[:id]).destroy
    flash[:warning] = "Image Deleted"
    redirect_to "/images"
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<div class = "container-fluid">
  <div class = "col-md-4"></div>
  <div class = "col-md-4">
    <%= form_tag "/images/#{@image.id}", method: :patch do %>
      <div class = "form-group">
        <p><%= label_tag :product_name %></p>
        <p><%= text_field_tag :product_name, @image.product.name, class: "form-control" %></p>
      </div>
      <div class = "form-group">
        <p><%= label_tag :url %></p>
        <p><%= text_field_tag :url, @image.url, class: "form-control"%></p>
      </div>
      <%= submit_tag "Submit Changes" %>
    <% end %>
  </div>
</div>

app/views/images/index.html.erb
<div class = "container-fluid">
  <div class = "row">
    <% @images.each_with_index do |image, index| %>
      <div class = "col-md-3" >
        <a href="/images/<%= image.id %>">
          <div class = "index-item">
                <div>
                  <img class = "img-responsive img-rounded" src=<%= image.url %>>
                </div>
          </div>  
        </a>
      </div>
    <% end %>
  </div>
  <div class = "row">
    <div class = "col-md-4"></div>
    <div class = "col-md-4">
      <p class = "center-text"><%= link_to "Add A New Image To The Database", new_image_path%></p>
    </div>
  </div>
</div>

app/views/images/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <h3 class = "center-text">New Image Entry Form</h3>
      <%= form_tag '/images', method: :post do %>
        <div class="form-group">
          <%= label_tag :name, "Product Name" %>
          <%= text_field_tag :name, @fruit_name, class: "form-control" %>
        </div>      
        <div class="form-group">
          <%= label_tag :url, "Image URL" %>
          <%= text_field_tag :url,"", class: "form-control" %>
        </div>
        <div class="form-group center-text">
          <%= submit_tag "Submit Image", class: "btn btn-default btn-lg" %>
        </div>
      <% end %>
      <div class="form-group center-text">
          <%= link_to "Abort Mission", "/products", class: "btn btn-default btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/images/show.html.erb
<div class = "container-fluid">
  <div class = "col-md-3">
  </div>
  <div class = "col-md-6 individual-product">
    <h3>Image</h3>
    <p><img class="img-responsive individual-image" src=<%= @image.url %>></p>
    <h3>Product</h3>
    <p><%= @image.product.name %></p>
    <p><%= link_to "Edit Image", edit_image_path, method: :get, class: "btn btn-default btn-lg" %></p>
    <p><a href="/images"><button class = "btn btn-default btn-lg">Back to All Images</button></a></p>
  </div>
</div>